version: "0.1"
services:
    d256_server:
        image: pabloalarconm/d256_server:0.1.0
        ports:
            - "8080:8080"

    256_client:
        image: pabloalarconm/d256_client:0.1.0
        ports:
            - "4200:4200"
        